name: Change Shell

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "${{ github.event.head_commit.message }}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
