name: Compare Functions

on: push

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello, World!', 'World') }} # 「World」を含むか
          CONTAINS_FUNC_2: ${{ contains(github.event.issue.labels.*.name, 'bug') }} # 配列に「bug」が含まれるか
          STARTS_WITH_FUNC: ${{ startsWith('Hello, World!', 'He') }} # 「He」で始まるか
          ENDS_WITH_FUNC: ${{ endsWith('Hello, World!', 'ld') }} # 「ld」で終わるか
