name: Conditions Workflow

on: push

jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      if: ${{ github.actor == 'cidkumagai' }} # cidkumagai以外はスキップ
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello"
