name: Contexts

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.actor }} # github コンテキストの参照
      - run: echo "${GITHUB_ACTOR}" # コンテキストではなくデフォルト環境変数を指定(アンチパターン)