name: Matrix

on: push

jobs:
  print:
    strategy:
      matrix: # マトリックスの定義
        os: [ubuntu-latest, windows-latest, macos-latest] # osプロパティの参照
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${RUNNER_OS}"
        shell: bash